language: c
script: ./scripts/travis-build.sh
env:
    - PROJECT=qemu-virt-a15-test        TOOLCHAIN=arm-eabi-5.2.0-Linux-x86_64
    - PROJECT=qemu-virt-a53-test        TOOLCHAIN=aarch-elf-5.2.0-Linux-x86_64
    - PROJECT=zybo-test                 TOOLCHAIN=arm-eabi-5.2.0-Linux-x86_64
    - PROJECT=stm32746g-eval2-test      TOOLCHAIN=arm-eabi-5.2.0-Linux-x86_64
    - PROJECT=stm32f746g-disco-test     TOOLCHAIN=arm-eabi-5.2.0-Linux-x86_64

    - PROJECT=vexpress-a9-test          TOOLCHAIN=arm-eabi-4.8.2-Linux-x86_64

# run in a container
sudo: false

# try to cache the toolchain download
cache:
  directories:
  - archives

# notify a few irc channels
notifications:
  irc:
    - "chat.freenode.net#lk"
    - "chat.freenode.net#fnlk"

